### ISSUE TITLE
fail to precompile

### ISSUE THREAD

**Issue by babaq** [JuliaImages/ImageDistances.jl#20] opened 2019-05-04 21:30 UTC
I just do a package update, and when I `using Images`, it failed on precompile with this message:
```julia
using Images
[ Info: Precompiling Images [916415d5-f1e6-5110-898d-aaa5f9f070e0]
ERROR: LoadError: UndefVarError: Colorant not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at .\boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include(::Module, ::String) at .\sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:328 [inlined]
 [7] eval(::Expr) at .\client.jl:404
 [8] top-level scope at .\none:3
in expression starting at C:\Users\Alex\.julia\packages\ImageDistances\NPLCx\src\ImageDistances.jl:22
ERROR: LoadError: Failed to precompile ImageDistances [51556ac3-7006-55f5-8cb3-34580c88182d] to C:\Users\Alex\.julia\compiled\v1.1\ImageDistances\lg0Xg.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853
 [6] include at .\boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1038
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:328 [inlined]
 [11] eval(::Expr) at .\client.jl:404
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Alex\.julia\packages\Images\BEHlD\src\Images.jl:52
ERROR: Failed to precompile Images [916415d5-f1e6-5110-898d-aaa5f9f070e0] to C:\Users\Alex\.julia\compiled\v1.1\Images\H8Vxc.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853
```
the `Images` version is v0.18.0, and `ImageDistances` is v0.2.2.

**Comment by juliohm** [comment] 2019-05-04 21:32
@johnnychen94 could you please take a look at this? Thanks.

**Comment by johnnychen94** [comment] 2019-05-04 23:15
@babaq That’s possibly a problem with ImageCore version, can you provide a detailed result of your packages list ( for example, run ‘]st’ in julia) ?

Thanks

**Comment by johnnychen94** [comment] 2019-05-05 00:08
@juliohm Colors and FixedPointNumbers are reexport from ImageCore since v0.8.1, so that we don’t need directly dependent on them in ImageDistances.

**Comment by juliohm** [comment] 2019-05-05 00:16
Please feel free to remove dependencies if they are not needed. That is
always great.

**Comment by babaq** [comment] 2019-05-05 01:11
@johnnychen94  the `ImageCore` is on 0.8.2, I've downgraded the `ImageDistances` to v0.2.1, and all works fine.

@juliohm I don't know how to explictely remove `ImageDistances` since I never explictely add this dependency, it's required by `Images`, and I need some of image filtering functions.

**Comment by johnnychen94** [comment] 2019-05-05 01:28
That's weird, can you provide the detailed information of your system and packages, or minimal reproducing procedure? (For example, the results of `versioninfo()` and `]st`)

I checked it using julia docker, which works normally.
<details>
  <summary> julia v1.0 </summary>

```julia
 bash $ docker run -it julia        
                                                                                                                                                                                                              
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_PATH = /usr/local/julia
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_VERSION = 1.0.0

(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`

(v1.0) pkg> add Images
   Cloning default registries into /root/.julia/registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Conda ───────────────────── v1.2.0
 Installed TiledIteration ──────────── v0.2.3
 Installed ImageMorphology ─────────── v0.2.1
 Installed BinaryProvider ──────────── v0.5.4
 Installed CSTParser ───────────────── v0.5.2
 Installed DataStructures ──────────── v0.15.0
 Installed Images ──────────────────── v0.18.0
 Installed Colors ──────────────────── v0.9.5
 Installed ImageDistances ──────────── v0.2.2
 Installed CoordinateTransformations ─ v0.5.0
 Installed FixedPointNumbers ───────── v0.5.3
 Installed IterTools ───────────────── v1.1.1
 Installed Ratios ──────────────────── v0.3.1
 Installed MacroTools ──────────────── v0.5.0
 Installed PaddedViews ─────────────── v0.4.2
 Installed AxisAlgorithms ──────────── v0.3.0
 Installed ImageMetadata ───────────── v0.7.0
 Installed FileIO ──────────────────── v1.0.6
 Installed RangeArrays ─────────────── v0.3.1
 Installed Compat ──────────────────── v2.1.0
 Installed ComputationalResources ──── v0.3.0
 Installed ImageTransformations ────── v0.8.0
 Installed SimpleTraits ────────────── v0.8.0
 Installed CatIndices ──────────────── v0.2.0
 Installed Requires ────────────────── v0.5.2
 Installed IndirectArrays ──────────── v0.5.0
 Installed URIParser ───────────────── v0.4.0
 Installed Graphics ────────────────── v0.4.0
 Installed IdentityRanges ──────────── v0.3.0
 Installed ColorVectorSpace ────────── v0.7.0
 Installed NaNMath ─────────────────── v0.3.2
 Installed JSON ────────────────────── v0.20.0
 Installed ImageShow ───────────────── v0.2.0
 Installed ImageAxes ───────────────── v0.6.0
 Installed FFTViews ────────────────── v0.2.0
 Installed Missings ────────────────── v0.4.0
 Installed ImageCore ───────────────── v0.8.2
 Installed Interpolations ──────────── v0.11.2
 Installed VersionParsing ──────────── v1.1.3
 Installed OffsetArrays ────────────── v0.11.0
 Installed FFTW ────────────────────── v0.2.4
 Installed SortingAlgorithms ───────── v0.3.1
 Installed Tokenize ────────────────── v0.5.3
 Installed Reexport ────────────────── v0.2.0
 Installed CustomUnitRanges ────────── v0.2.0
 Installed IntervalSets ────────────── v0.3.1
 Installed Distances ───────────────── v0.8.0
 Installed ColorTypes ──────────────── v0.7.5
 Installed AbstractFFTs ────────────── v0.4.0
 Installed SpecialFunctions ────────── v0.7.2
 Installed ImageFiltering ──────────── v0.6.1
 Installed AxisArrays ──────────────── v0.3.0
 Installed WoodburyMatrices ────────── v0.4.1
 Installed Rotations ───────────────── v0.11.1
 Installed BinDeps ─────────────────── v0.8.10
 Installed OrderedCollections ──────── v1.1.0
 Installed MappedArrays ────────────── v0.2.1
 Installed StatsBase ───────────────── v0.30.0
 Installed StaticArrays ────────────── v0.10.3
  Updating `~/.julia/environments/v1.0/Project.toml`
  [916415d5] + Images v0.18.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [621f4979] + AbstractFFTs v0.4.0
  [13072b0f] + AxisAlgorithms v0.3.0
  [39de3d68] + AxisArrays v0.3.0
  [9e28174c] + BinDeps v0.8.10
  [b99e7846] + BinaryProvider v0.5.4
  [00ebfdb7] + CSTParser v0.5.2
  [aafaddc9] + CatIndices v0.2.0
  [3da002f7] + ColorTypes v0.7.5
  [c3611d14] + ColorVectorSpace v0.7.0
  [5ae59095] + Colors v0.9.5
  [34da2185] + Compat v2.1.0
  [ed09eef8] + ComputationalResources v0.3.0
  [8f4d0f93] + Conda v1.2.0
  [150eb455] + CoordinateTransformations v0.5.0
  [dc8bdbbb] + CustomUnitRanges v0.2.0
  [864edb3b] + DataStructures v0.15.0
  [b4f34e82] + Distances v0.8.0
  [4f61f5a4] + FFTViews v0.2.0
  [7a1cc6ca] + FFTW v0.2.4
  [5789e2e9] + FileIO v1.0.6
  [53c48c17] + FixedPointNumbers v0.5.3
  [a2bd30eb] + Graphics v0.4.0
  [bbac6d45] + IdentityRanges v0.3.0
  [2803e5a7] + ImageAxes v0.6.0
  [a09fc81d] + ImageCore v0.8.2
  [51556ac3] + ImageDistances v0.2.2
  [6a3955dd] + ImageFiltering v0.6.1
  [bc367c6b] + ImageMetadata v0.7.0
  [787d08f9] + ImageMorphology v0.2.1
  [4e3cecfd] + ImageShow v0.2.0
  [02fcd773] + ImageTransformations v0.8.0
  [916415d5] + Images v0.18.0
  [9b13fd28] + IndirectArrays v0.5.0
  [a98d9a8b] + Interpolations v0.11.2
  [8197267c] + IntervalSets v0.3.1
  [c8e1da08] + IterTools v1.1.1
  [682c06a0] + JSON v0.20.0
  [1914dd2f] + MacroTools v0.5.0
  [dbb5928d] + MappedArrays v0.2.1
  [e1d29d7a] + Missings v0.4.0
  [77ba4419] + NaNMath v0.3.2
  [6fe1bfb0] + OffsetArrays v0.11.0
  [bac558e1] + OrderedCollections v1.1.0
  [5432bcbf] + PaddedViews v0.4.2
  [b3c3ace0] + RangeArrays v0.3.1
  [c84ed2f1] + Ratios v0.3.1
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v0.5.2
  [6038ab10] + Rotations v0.11.1
  [699a6c99] + SimpleTraits v0.8.0
  [a2af1166] + SortingAlgorithms v0.3.1
  [276daf66] + SpecialFunctions v0.7.2
  [90137ffa] + StaticArrays v0.10.3
  [2913bbd2] + StatsBase v0.30.0
  [06e1c1a7] + TiledIteration v0.2.3
  [0796e94c] + Tokenize v0.5.3
  [30578b45] + URIParser v0.4.0
  [81def892] + VersionParsing v1.1.3
  [efce3f68] + WoodburyMatrices v0.4.1
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 
  Building Conda ───────────→ `~/.julia/packages/Conda/CpuvI/deps/build.log`
  Building FFTW ────────────→ `~/.julia/packages/FFTW/p7sLQ/deps/build.log`
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`

julia> using Images
[ Info: Precompiling Images [916415d5-f1e6-5110-898d-aaa5f9f070e0]

julia> 
```
</details>

I'm sorry for bringing this trouble.

**Comment by babaq** [comment] 2019-05-05 03:07
```Julia
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

```julia
(v1.1) pkg> st
    Status `C:\Users\Alex\.julia\environments\v1.1\Project.toml`
  [c52e3926] Atom v0.8.5
  [fbb218c0] BSON v0.2.3
  [336ed68f] CSV v0.5.0
  [c3611d14] ColorVectorSpace v0.6.2
  [5ae59095] Colors v0.9.5
  [717857b8] DSP v0.5.2
  [a93c6f00] DataFrames v0.18.2
  [864edb3b] DataStructures v0.15.0
  [39dd38d3] Dierckx v0.4.1
  [31c24e10] Distributions v0.18.0
  [becb17da] Feather v0.5.1
  [5789e2e9] FileIO v1.0.6
  [587475ba] Flux v0.8.3
  [19dc6840] HCubature v1.3.0
  [f67ccb44] HDF5 v0.11.1
  [7073ff75] IJulia v1.18.1
  [51556ac3] ImageDistances v0.2.1
  [6218d12a] ImageMagick v0.7.3
  [916415d5] Images v0.18.0
  [c601a237] Interact v0.10.2
  [a98d9a8b] Interpolations v0.11.2
  [4138dd39] JLD v0.9.1
  [033835bb] JLD2 v0.1.2
  [e5e0dc1b] Juno v0.7.0
  [2fda8390] LsqFit v0.8.1
  [23992714] MAT v0.5.0
  [ee78f7c6] Makie v0.9.3
  [6f286f6a] MultivariateStats v0.6.0
  [47be7bcc] ORCA v0.2.1
  [f0f68f2c] PlotlyJS v0.12.3
  [91a5bcdd] Plots v0.24.0
  [92933f4c] ProgressMeter v0.9.0
  [d330b81b] PyPlot v2.8.1
  [295af30f] Revise v2.1.3
  [2913bbd2] StatsBase v0.30.0
  [f3b207a7] StatsPlots v0.10.2
  [bd369af6] Tables v0.2.0
  [1986cc42] Unitful v0.15.0
  [0f1e0344] WebIO v0.8.1
  [ddb6d928] YAML v0.3.2
  [37e2e46d] LinearAlgebra
```

**Comment by johnnychen94** [comment] 2019-05-05 03:52
I see, thanks for the report. The ImageCore version is too old, it's actually `ImageCore v0.7.4`.

We're in the progress of switching to new package registrator, `Makie` in your `Project.toml` doesn't support `ImageCore 0.8.1`, but this requires some time to fix in other packages. I've reported this in https://github.com/JuliaPlots/GLMakie.jl/issues/33

In the meantime, I'll make some compatibility changes in ImageDistances to support `ImageCore 0.7.4` and bump a version (luckily this can be fixed in 1-3 days I suppose)

Best

**Comment by johnnychen94** [comment] 2019-05-05 10:32
`ImageDistances v0.2.3` is now compatible to `ImageCore v0.7.4`

**Closed by johnnychen94** 2019-05-05 10:32 UTC
